title: frontendnode
description: >- # this means to ignore newlines until "baseurl:"
  Frontendnode is a programming blog and tutorials about web development, Javascript, Typescript, Python, Ruby, Jekyll and Hugo etc.
baseurl: "/" # e.g. /blog
url: "https://frontendnode.com" # e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
syntax:
  theme: stackoverflow-light

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:title

sass:
  sass_dir: _sass
  style: compressed

collections:
  pages:
    output: true
    permalink: :title/